#
# (C) Copyright 2000, 2001, 2002
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Guennadi Liakhovetki, DENX Software Engineering, <lg@denx.de>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= tiny4412.o
obj-y	+= lowlevel_init.o
obj-y   += clock_init_tiny4412.o
obj-y   += mem_init_tiny4412.o
